// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSZHMgfenl1hAAEyUzftcSC38E_KGtBE4',
    appId: '1:622509211896:web:066e6194bccc61ad897b0d',
    messagingSenderId: '622509211896',
    projectId: 'survey-app-with-spreadsheet',
    authDomain: 'survey-app-with-spreadsheet.firebaseapp.com',
    storageBucket: 'survey-app-with-spreadsheet.appspot.com',
    measurementId: 'G-KNQ09X01PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU061nLvqsQvqU4paDwhVtDSQ1JR9SJAc',
    appId: '1:622509211896:android:af77b0f8b0da64b9897b0d',
    messagingSenderId: '622509211896',
    projectId: 'survey-app-with-spreadsheet',
    storageBucket: 'survey-app-with-spreadsheet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFKJbp0eFehxcMz5ZusoGR6BcH7k6oQSY',
    appId: '1:622509211896:ios:68ee553f5fbfddb8897b0d',
    messagingSenderId: '622509211896',
    projectId: 'survey-app-with-spreadsheet',
    storageBucket: 'survey-app-with-spreadsheet.appspot.com',
    iosBundleId: 'com.example.surveyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFKJbp0eFehxcMz5ZusoGR6BcH7k6oQSY',
    appId: '1:622509211896:ios:68ee553f5fbfddb8897b0d',
    messagingSenderId: '622509211896',
    projectId: 'survey-app-with-spreadsheet',
    storageBucket: 'survey-app-with-spreadsheet.appspot.com',
    iosBundleId: 'com.example.surveyApp',
  );
}
